/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteErezArgs } from "./DeleteErezArgs";
import { ErezCountArgs } from "./ErezCountArgs";
import { ErezFindManyArgs } from "./ErezFindManyArgs";
import { ErezFindUniqueArgs } from "./ErezFindUniqueArgs";
import { Erez } from "./Erez";
import { ErezService } from "../erez.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Erez)
export class ErezResolverBase {
  constructor(
    protected readonly service: ErezService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Erez",
    action: "read",
    possession: "any",
  })
  async _erezsMeta(
    @graphql.Args() args: ErezCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Erez])
  @nestAccessControl.UseRoles({
    resource: "Erez",
    action: "read",
    possession: "any",
  })
  async erezs(@graphql.Args() args: ErezFindManyArgs): Promise<Erez[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Erez, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Erez",
    action: "read",
    possession: "own",
  })
  async erez(@graphql.Args() args: ErezFindUniqueArgs): Promise<Erez | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Erez)
  @nestAccessControl.UseRoles({
    resource: "Erez",
    action: "delete",
    possession: "any",
  })
  async deleteErez(@graphql.Args() args: DeleteErezArgs): Promise<Erez | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
